# Generated by Django 5.1.2 on 2024-11-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pickup_date',
        ),
    ]
